storage:
  dbPath: /home/mongodb/data
net:
  bindIp: 0.0.0.0
  port: 27017
  tls:
    mode: requireTLS
    certificateKeyFile: /home/mongodb/certs/mongodb_tls.pem
    CAFile: /home/mongodb/certs/cert.pem
systemLog:
  destination: file
  path: /home/mongodb/logs/mongod.log
  logAppend: true